### ISSUE TITLE
the arguments in the readme are swapped

### ISSUE THREAD

**Issue by Sagleft** [mitranim/jsonfmt#2]
specified:
```go
formatted := jsonfmt.FormatString(`{}`, jsonfmt.Default)
```

should be:
```go
formatted := jsonfmt.FormatString(jsonfmt.Default, `{}`)
```

**Comment by mitranim** [comment]
Turns out, this is just an outdated example in the readme. I've changed the API recently to have a signature like your second example. Pushed a fix. Thanks!
